### ISSUE TITLE
Do I need to root the phone first for it to work?

### ISSUE THREAD

**Issue by saintnever** [mohaseeb/wisture#1]
I tried to run it on Samsung Galaxy S8+, but the chart shows nothing, and the file is 0B.

**Comment by ramviyas** [comment]
No, it does not need to be rooted. Can you please share more info on your issue?

**Comment by saintnever** [comment]
I really don't have more useful info on this... Ran it on Galaxy S8+, clicked start, the chart showed no data, and the saved file is empty. WiFi was on, and other similar program worked fine.

**Comment by mohaseeb** [comment]
@saintnever 
To be able to sample the Wi-Fi RSSI at a frequency higher than what was available through the Android API, this app reads the Wi-Fi RSSI measurements from the "wireless extension for Linux" user interface; i.e by reading the pseudo file /proc/net/wireless. In some phones, the RSSI measurements are not reported to this interface.

To see if there is another reason/bug, can you install a [terminal app](https://play.google.com/store/apps/details?id=com.kibou.androidshell&hl=en) in your phone and run `cat /proc/net/wireless` while WiFi is ON. If the Wi-Fi stats are reported correctly, you should see non-zero values in the command output.
